GET http://localhost:3000/user

###

GET http://localhost:3000/user/2

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "firstname": "Billy",
    "lastname": "Bob",
    "age": "51"
}

###

DELETE http://localhost:3000/user/6

###

PATCH http://localhost:3000/user/5
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Smith",
    "age": 34
}